services:
  app:
    build: 
      context: .
    ports:
      - 6969:6969
    environment:
      PG_HOST: db
      PG_USER: mayank
      PG_PASSWORD: zeotap
      PG_DATABASE: zeotapdb
      PG_PORT: 5432
      API_KEY: 38b7407fbdb233c5be49085f145985ae
      PORT: 6969  
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: mayank
      POSTGRES_PASSWORD: zeotap
      POSTGRES_DB: zeotapdb
    ports:
      - "5431:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data 
volumes:
  pgdata:
networks:
  zeotapnetwork: